import { mysqlTable, mysqlSchema, AnyMySqlColumn, index, varchar, int, timestamp, mysqlEnum, text, decimal } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const agentAssignments = mysqlTable("agent_assignments", {
	id: varchar({ length: 64 }).notNull(),
	tenantId: int().notNull(),
	agentName: varchar({ length: 255 }).notNull(),
	planId: varchar({ length: 64 }).notNull(),
	teamId: varchar({ length: 64 }),
	anniversaryDate: varchar({ length: 5 }),
	startDate: varchar({ length: 10 }),
	isActive: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("agent_assignments_tenant_agent_unique").on(table.tenantId, table.agentName),
	index("agent_assignments_tenant_idx").on(table.tenantId),
	index("agent_assignments_agent_idx").on(table.agentName),
	index("agent_assignments_plan_idx").on(table.planId),
	index("agent_assignments_team_idx").on(table.teamId),
	index("agent_assignments_active_idx").on(table.isActive),
]);

export const auditLogs = mysqlTable("audit_logs", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull(),
	adminId: int().notNull(),
	adminName: varchar({ length: 255 }).notNull(),
	adminEmail: varchar({ length: 320 }),
	action: mysqlEnum(['user_created','user_deleted','user_role_changed','upload_deleted','upload_viewed','settings_changed','data_exported','tenant_settings_changed','oauth_connected','oauth_disconnected']).notNull(),
	targetType: mysqlEnum(['user','upload','system','tenant']),
	targetId: int(),
	targetName: varchar({ length: 255 }),
	details: text(),
	ipAddress: varchar({ length: 45 }),
	userAgent: text(),
	createdAt: timestamp({ fsp: 3, mode: 'string' }).default('CURRENT_TIMESTAMP(3)').notNull(),
},
(table) => [
	index("tenant_idx").on(table.tenantId),
	index("action_idx").on(table.action),
	index("adminId_idx").on(table.adminId),
	index("tenant_createdAt_idx").on(table.tenantId, table.createdAt),
	index("adminId_createdAt_idx").on(table.adminId, table.createdAt),
	index("targetType_targetId_idx").on(table.targetType, table.targetId),
]);

export const cdaFieldMappings = mysqlTable("cda_field_mappings", {
	id: int().autoincrement().notNull(),
	templateId: varchar({ length: 64 }).notNull(),
	csvColumn: varchar({ length: 255 }),
	cdaField: varchar({ length: 255 }).notNull(),
	transformFunction: varchar({ length: 100 }),
	defaultValue: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("cda_field_mappings_template_idx").on(table.templateId),
	index("cda_field_mappings_cda_field_idx").on(table.cdaField),
]);

export const cdaGenerated = mysqlTable("cda_generated", {
	id: varchar({ length: 64 }).notNull(),
	tenantId: int().notNull(),
	templateId: varchar({ length: 64 }).notNull(),
	transactionId: varchar({ length: 64 }),
	propertyAddress: varchar({ length: 500 }),
	mlsNumber: varchar({ length: 100 }),
	salePrice: decimal({ precision: 12, scale: 2 }),
	closingDate: varchar({ length: 10 }),
	grossCommission: decimal({ precision: 12, scale: 2 }),
	commissionRate: decimal({ precision: 5, scale: 2 }),
	pdfPath: text(),
	pdfFileName: varchar({ length: 255 }),
	status: mysqlEnum(['draft','pending_approval','approved','sent','completed']).default('draft').notNull(),
	generatedBy: int().notNull(),
	generatedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	approvedBy: int(),
	approvedAt: timestamp({ mode: 'string' }),
	sentAt: timestamp({ mode: 'string' }),
	calculationData: text(),
	notes: text(),
},
(table) => [
	index("cda_generated_tenant_idx").on(table.tenantId),
	index("cda_generated_template_idx").on(table.templateId),
	index("cda_generated_transaction_idx").on(table.transactionId),
	index("cda_generated_status_idx").on(table.status),
	index("cda_generated_generated_by_idx").on(table.generatedBy),
	index("cda_generated_generated_at_idx").on(table.generatedAt),
]);

export const cdaTemplates = mysqlTable("cda_templates", {
	id: varchar({ length: 64 }).notNull(),
	tenantId: int().notNull(),
	name: varchar({ length: 255 }).notNull(),
	brokerageName: varchar({ length: 255 }).notNull(),
	brokerageAddress: text(),
	brokerageLogo: text(),
	brokerName: varchar({ length: 255 }),
	brokerEmail: varchar({ length: 320 }),
	brokerPhone: varchar({ length: 50 }),
	defaultSettings: text(),
	isActive: int().default(1).notNull(),
	createdBy: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("cda_templates_tenant_idx").on(table.tenantId),
	index("cda_templates_active_idx").on(table.isActive),
	index("cda_templates_created_by_idx").on(table.createdBy),
]);

export const commissionCalculations = mysqlTable("commission_calculations", {
	id: varchar({ length: 64 }).notNull(),
	tenantId: int().notNull(),
	uploadId: int(),
	calculationDate: varchar({ length: 10 }).notNull(),
	breakdowns: text().notNull(),
	ytdSummaries: text().notNull(),
	transactionCount: int().notNull(),
	agentCount: int().notNull(),
	totalCompanyDollar: int().notNull(),
	totalGrossCommission: int().notNull(),
	createdBy: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("commission_calculations_tenant_idx").on(table.tenantId),
	index("commission_calculations_date_idx").on(table.calculationDate),
	index("commission_calculations_upload_idx").on(table.uploadId),
]);

export const commissionPlans = mysqlTable("commission_plans", {
	id: varchar({ length: 64 }).notNull(),
	tenantId: int().notNull(),
	name: varchar({ length: 255 }).notNull(),
	splitPercentage: int().notNull(),
	capAmount: int().default(0).notNull(),
	postCapSplit: int().default(100).notNull(),
	deductions: text(),
	royaltyPercentage: int(),
	royaltyCap: int(),
	description: text(),
	isActive: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	useSliding: int().default(0).notNull(),
	tiers: text(),
},
(table) => [
	index("commission_plans_tenant_idx").on(table.tenantId),
	index("commission_plans_active_idx").on(table.isActive),
]);

export const oauthTokens = mysqlTable("oauth_tokens", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull(),
	userId: int().notNull(),
	provider: varchar({ length: 50 }).default('dotloop').notNull(),
	encryptedAccessToken: text().notNull(),
	encryptedRefreshToken: text().notNull(),
	tokenExpiresAt: timestamp({ mode: 'string' }).notNull(),
	encryptionKeyVersion: int().default(1).notNull(),
	tokenHash: varchar({ length: 64 }).notNull(),
	ipAddress: varchar({ length: 45 }),
	userAgent: text(),
	deviceFingerprint: varchar({ length: 255 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	lastUsedAt: timestamp({ mode: 'string' }),
	lastRefreshedAt: timestamp({ mode: 'string' }),
	dotloopAccountId: int(),
	dotloopProfileId: int(),
	dotloopDefaultProfileId: int(),
	dotloopProfileIds: text(),
	connectionName: varchar({ length: 255 }),
	isActive: int().default(1).notNull(),
	isPrimary: int().default(0).notNull(),
	dotloopAccountEmail: varchar({ length: 320 }),
	dotloopAccountName: varchar({ length: 255 }),
},
(table) => [
	index("oauth_tokens_tokenHash_unique").on(table.tokenHash),
	index("tenant_idx").on(table.tenantId),
	index("user_idx").on(table.userId),
	index("tokenHash_idx").on(table.tokenHash),
	index("expires_idx").on(table.tokenExpiresAt),
	index("tenant_provider_idx").on(table.tenantId, table.provider),
	index("tenant_user_provider_idx").on(table.tenantId, table.userId, table.provider),
	index("oauth_tokens_primary_idx").on(table.userId, table.isPrimary),
]);

export const platformAdminLogs = mysqlTable("platform_admin_logs", {
	id: int().autoincrement().notNull(),
	adminUserId: int().notNull(),
	tenantId: int(),
	action: varchar({ length: 100 }).notNull(),
	reason: text(),
	details: text(),
	ipAddress: varchar({ length: 45 }).notNull(),
	userAgent: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("admin_idx").on(table.adminUserId),
	index("tenant_idx").on(table.tenantId),
	index("time_idx").on(table.createdAt),
	index("admin_time_idx").on(table.adminUserId, table.createdAt),
	index("tenant_time_idx").on(table.tenantId, table.createdAt),
]);

export const teams = mysqlTable("teams", {
	id: varchar({ length: 64 }).notNull(),
	tenantId: int().notNull(),
	name: varchar({ length: 255 }).notNull(),
	leadAgent: varchar({ length: 255 }).notNull(),
	teamSplitPercentage: int().notNull(),
	description: text(),
	isActive: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("teams_tenant_idx").on(table.tenantId),
	index("teams_active_idx").on(table.isActive),
]);

export const tenantMembers = mysqlTable("tenant_members", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull(),
	userId: int().notNull(),
	role: mysqlEnum(['admin','broker','member','agent']).notNull(),
	joinedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	invitedBy: int(),
	invitedAt: timestamp({ mode: 'string' }),
	status: mysqlEnum(['active','invited','inactive']).default('active').notNull(),
	permissions: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("tenant_members_tenant_idx").on(table.tenantId),
	index("tenant_members_user_idx").on(table.userId),
	index("tenant_members_tenant_user_unique").on(table.tenantId, table.userId),
	index("tenant_members_role_idx").on(table.role),
	index("tenant_members_status_idx").on(table.status),
]);

export const tenants = mysqlTable("tenants", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 255 }).notNull(),
	subdomain: varchar({ length: 63 }).notNull(),
	customDomain: varchar({ length: 255 }),
	status: mysqlEnum(['active','suspended','deleted']).default('active').notNull(),
	subscriptionTier: mysqlEnum(['free','basic','professional','enterprise']).default('free').notNull(),
	settings: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("tenants_subdomain_unique").on(table.subdomain),
	index("tenants_customDomain_unique").on(table.customDomain),
	index("subdomain_idx").on(table.subdomain),
	index("customDomain_idx").on(table.customDomain),
]);

export const tierHistory = mysqlTable("tier_history", {
	id: varchar({ length: 64 }).notNull(),
	tenantId: int().notNull(),
	agentName: varchar({ length: 255 }).notNull(),
	planId: varchar({ length: 64 }).notNull(),
	previousTierIndex: int(),
	previousTierThreshold: int(),
	previousSplitPercentage: int(),
	newTierIndex: int().notNull(),
	newTierThreshold: int().notNull(),
	newSplitPercentage: int().notNull(),
	ytdAmount: int().notNull(),
	transactionId: varchar({ length: 255 }),
	transactionDate: varchar({ length: 50 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("tier_history_tenant_idx").on(table.tenantId),
	index("tier_history_agent_idx").on(table.agentName),
	index("tier_history_plan_idx").on(table.planId),
	index("tier_history_tenant_agent_idx").on(table.tenantId, table.agentName),
	index("tier_history_created_idx").on(table.createdAt),
]);

export const tokenAuditLogs = mysqlTable("token_audit_logs", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull(),
	userId: int(),
	tokenId: int(),
	action: mysqlEnum(['token_created','token_refreshed','token_used','token_revoked','token_decryption_failed','suspicious_access','rate_limit_exceeded','security_alert']).notNull(),
	status: mysqlEnum(['success','failure','warning']).notNull(),
	errorMessage: text(),
	ipAddress: varchar({ length: 45 }).notNull(),
	userAgent: text(),
	requestId: varchar({ length: 255 }),
	metadata: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("tenant_time_idx").on(table.tenantId, table.createdAt),
	index("action_idx").on(table.action, table.createdAt),
	index("suspicious_idx").on(table.tenantId, table.createdAt, table.action),
]);

export const transactions = mysqlTable("transactions", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull(),
	uploadId: int().notNull(),
	userId: int().notNull(),
	loopId: varchar({ length: 255 }),
	loopViewUrl: text(),
	loopName: varchar({ length: 500 }),
	loopStatus: varchar({ length: 100 }),
	createdDate: varchar({ length: 50 }),
	closingDate: varchar({ length: 50 }),
	listingDate: varchar({ length: 50 }),
	offerDate: varchar({ length: 50 }),
	address: text(),
	price: int(),
	propertyType: varchar({ length: 100 }),
	bedrooms: int(),
	bathrooms: int(),
	squareFootage: int(),
	city: varchar({ length: 100 }),
	state: varchar({ length: 50 }),
	county: varchar({ length: 100 }),
	leadSource: varchar({ length: 100 }),
	agents: text(),
	createdBy: varchar({ length: 255 }),
	earnestMoney: int(),
	salePrice: int(),
	commissionRate: int(),
	commissionTotal: int(),
	buySideCommission: int(),
	sellSideCommission: int(),
	companyDollar: int(),
	referralSource: varchar({ length: 255 }),
	referralPercentage: int(),
	complianceStatus: varchar({ length: 100 }),
	tags: text(),
	originalPrice: int(),
	yearBuilt: int(),
	lotSize: int(),
	subdivision: varchar({ length: 255 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("loopId_tenant_unique").on(table.loopId, table.tenantId),
	index("tenant_idx").on(table.tenantId),
	index("upload_idx").on(table.uploadId),
	index("user_idx").on(table.userId),
	index("uploadId_user_idx").on(table.uploadId, table.userId),
	index("user_createdAt_idx").on(table.userId, table.createdAt),
	index("tenant_createdAt_idx").on(table.tenantId, table.createdAt),
]);

export const uploadActivityLog = mysqlTable("upload_activity_log", {
	id: int().autoincrement().notNull(),
	uploadId: int().notNull(),
	userTeamId: int().notNull(),
	userId: int().notNull(),
	action: mysqlEnum(['shared','viewed','downloaded','deleted']).notNull(),
	details: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("upload_idx").on(table.uploadId),
	index("user_team_idx").on(table.userTeamId),
	index("user_idx").on(table.userId),
	index("created_at_idx").on(table.createdAt),
]);

export const uploadSharing = mysqlTable("upload_sharing", {
	id: int().autoincrement().notNull(),
	uploadId: int().notNull(),
	userTeamId: int().notNull(),
	sharedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	sharedBy: int().notNull(),
},
(table) => [
	index("upload_idx").on(table.uploadId),
	index("user_team_idx").on(table.userTeamId),
	index("upload_user_team_unique").on(table.uploadId, table.userTeamId),
	index("shared_at_idx").on(table.sharedAt),
]);

export const uploadSnapshots = mysqlTable("upload_snapshots", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull(),
	uploadId: int().notNull(),
	fileName: varchar({ length: 255 }).notNull(),
	uploadedAt: timestamp({ mode: 'string' }).notNull(),
	totalTransactions: int().notNull(),
	totalSalesVolume: int().notNull(),
	averagePrice: int().notNull(),
	totalCommission: int().notNull(),
	closingRate: int().notNull(),
	avgDaysToClose: int().notNull(),
	activeListings: int().notNull(),
	underContract: int().notNull(),
	closedDeals: int().notNull(),
	archivedDeals: int().notNull(),
	totalCompanyDollar: int().notNull(),
	buySideCommission: int().notNull(),
	sellSideCommission: int().notNull(),
	metricsJson: text().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("upload_snapshots_tenant_idx").on(table.tenantId),
	index("upload_snapshots_upload_idx").on(table.uploadId),
	index("upload_snapshots_tenant_uploadedAt_idx").on(table.tenantId, table.uploadedAt),
	index("upload_snapshots_createdAt_idx").on(table.createdAt),
]);

export const uploads = mysqlTable("uploads", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull(),
	userId: int().notNull(),
	fileName: varchar({ length: 255 }).notNull(),
	recordCount: int().notNull(),
	uploadedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	fileSize: int(),
	validationTimeMs: int(),
	parsingTimeMs: int(),
	uploadTimeMs: int(),
	totalTimeMs: int(),
	status: mysqlEnum(['success','failed','partial']).default('success').notNull(),
	errorMessage: text(),
},
(table) => [
	index("tenant_idx").on(table.tenantId),
	index("user_idx").on(table.userId),
	index("user_uploadedAt_idx").on(table.userId, table.uploadedAt),
	index("tenant_uploadedAt_idx").on(table.tenantId, table.uploadedAt),
]);

export const userPreferences = mysqlTable("user_preferences", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	tenantId: int().notNull(),
	activeOauthTokenId: int(),
	defaultUploadView: varchar({ length: 50 }).default('dashboard'),
	theme: varchar({ length: 20 }).default('light'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
	commissionVisibility: mysqlEnum(['public','team','admin_only','private']).default('admin_only').notNull(),
	allowOthersViewMyCommission: int().default(0).notNull(),
	allowOthersViewMyTransactions: int().default(1).notNull(),
	showInLeaderboard: int().default(1).notNull(),
},
(table) => [
	index("user_preferences_user_unique").on(table.userId),
	index("user_preferences_tenant_idx").on(table.tenantId),
]);

export const userTeamMembers = mysqlTable("user_team_members", {
	id: int().autoincrement().notNull(),
	userTeamId: int().notNull(),
	userId: int().notNull(),
	role: mysqlEnum(['owner','editor','viewer']).default('viewer').notNull(),
	addedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	addedBy: int().notNull(),
},
(table) => [
	index("user_team_idx").on(table.userTeamId),
	index("user_idx").on(table.userId),
	index("user_team_user_unique").on(table.userTeamId, table.userId),
]);

export const userTeams = mysqlTable("user_teams", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull(),
	ownerId: int().notNull(),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("tenant_idx").on(table.tenantId),
	index("owner_idx").on(table.ownerId),
	index("tenant_owner_idx").on(table.tenantId, table.ownerId),
]);

export const users = mysqlTable("users", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull(),
	openId: varchar({ length: 64 }),
	dotloopUserId: varchar({ length: 64 }),
	name: text(),
	email: varchar({ length: 320 }),
	loginMethod: varchar({ length: 64 }),
	role: mysqlEnum(['admin','broker','agent','viewer']).default('viewer').notNull(),
	status: mysqlEnum(['active','inactive','suspended']).default('active').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	lastSignedIn: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("openId_tenant_unique").on(table.openId, table.tenantId),
	index("email_tenant_unique").on(table.email, table.tenantId),
	index("tenant_idx").on(table.tenantId),
	index("dotloopUserId_unique").on(table.dotloopUserId),
]);

export const brokerageBranding = mysqlTable("brokerage_branding", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull().unique(),
	brokerageName: varchar({ length: 255 }).notNull(),
	tagline: text(),
	address: text(),
	phone: varchar({ length: 20 }),
	licenseNumber: varchar({ length: 100 }),
	primaryColor: varchar({ length: 7 }).default('#10b981').notNull(),
	secondaryColor: varchar({ length: 7 }).default('#3b82f6').notNull(),
	accentColor: varchar({ length: 7 }).default('#8b5cf6').notNull(),
	logoUrl: text(),
	logoFileName: varchar({ length: 255 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("brokerage_branding_tenant_idx").on(table.tenantId),
]);

export const cdaDocuments = mysqlTable("cda_documents", {
	id: varchar({ length: 64 }).notNull(),
	tenantId: int().notNull(),
	documentName: varchar({ length: 255 }).notNull(),
	description: text(),
	transactionId: varchar({ length: 255 }),
	loopName: varchar({ length: 255 }),
	closingCompany: varchar({ length: 255 }),
	closingOfficer: varchar({ length: 255 }),
	propertyAddress: text(),
	salePrice: decimal({ precision: 15, scale: 2 }),
	closingDate: varchar({ length: 10 }),
	totalCommissionRate: decimal({ precision: 5, scale: 2 }),
	listingSide: decimal({ precision: 5, scale: 2 }),
	buyingSide: decimal({ precision: 5, scale: 2 }),
	referralFee: decimal({ precision: 5, scale: 2 }),
	franchiseFee: decimal({ precision: 5, scale: 2 }),
	listingAgentSplit: decimal({ precision: 5, scale: 2 }),
	buyingAgentSplit: decimal({ precision: 5, scale: 2 }),
	agentsData: text().notNull(),
	deductions: text(),
	disbursementInstructions: text(),
	pdfUrl: text(),
	pdfFileName: varchar({ length: 255 }),
	status: mysqlEnum(['draft','generated','approved','archived']).default('draft').notNull(),
	createdBy: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	approvedBy: int(),
	approvedAt: timestamp({ mode: 'string' }),
},
(table) => [
	index("cda_documents_tenant_idx").on(table.tenantId),
	index("cda_documents_status_idx").on(table.status),
	index("cda_documents_created_by_idx").on(table.createdBy),
	index("cda_documents_transaction_idx").on(table.transactionId),
	index("cda_documents_created_at_idx").on(table.createdAt),
]);
